---
title: "Maternal emotion socialization in early childhood predicts adolescents’ amygdala-vmPFC functional connectivity to emotion faces."
output:
  distill::distill_article:
    css: ../../../styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[<i class="fas fa-file-download"></i> PDF](static/pubs/20-2020-DevPsych/20.Chen-McCormick-Ravindran-McElwain-Telzer-2020-DevPsych.pdf) | [<i class="fas fa-quote-left"></i><i class="fas fa-quote-right"></i> BibTeX Citation](static/pubs/20-2020-DevPsych/cite.bib) | [<i class="ai ai-open-data"></i> Dataset](https://neurovault.org/collections/XMHSEZWX/) | [<i class="fas fa-link"></i> DOI](https://doi.org/10.1037/dev0000852)

### Abstract
Guided by Eisenberg, Cumberland, and Spinrad’s (1998) conceptual framework, we examined multiple components of maternal emotion socialization (i.e., reactions to children’s negative emotion, emotion talk, emotional expressiveness) at 33 months of age as predictors of adolescents’ amygdala-vmPFC connectivity and amygdala activation when labeling and passively observing angry and happy faces. For angry faces, more positive maternal emotion socialization behaviors predicted (a) less positive amygdala-vmPFC connectivity, which may reflect more mature vmPFC downregulation of the amygdala activation underlying implicit emotion regulation, and (b) more amygdala activation, which may reflect higher sensitivity to others’ emotional cues. Associations between negative emotion socialization behaviors and neural responses to angry faces were nonsignificant, and findings for the models predicting neural responses to happy faces showed a less consistent pattern. By expanding Eisenberg et al.’s (1998) framework to consider neural processing of negative emotions, the current findings point toward the potential long-term implications of positive emotion socialization experiences during early childhood for optimal functioning of the amygdala-vmPFC circuitry during adolescence.

**Citation:** Chen, X., McCormick, E. M., Ravindran, N., McElwain, N. L., & Telzer, E. H. (2020). Maternal emotion socialization in early childhood predicts adolescents’ amygdala-vmPFC functional connectivity to emotion faces. *Developmental Psychology, 56*(3), 503-515.