---
title: "Neural correlates of sibling closeness and association with externalizing behavior in adolescence."
output:
  distill::distill_article:
    css: ../../../styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[<i class="fas fa-file-download"></i> PDF](static/pubs/11-2018-SCAN/11.Rogers-McCormick-van-Hoorn-Ivory-Telzer-2018-SCAN.pdf) | [<i class="fas fa-quote-left"></i><i class="fas fa-quote-right"></i> BibTeX Citation](static/pubs/11-2018-SCAN/cite.bib) | [<i class="ai ai-open-data"></i> Dataset](https://neurovault.org/collections/3867/) | [<i class="fas fa-link"></i> DOI](https://doi.org/10.1093/scan/nsy063)

### Abstract
Sibling relationships have been linked to adolescent externalizing behaviors, but the neurobiological factors that underlie this association have not been identified. This study investigated sibling closeness and birth order as a predictor of adolescent externalizing behavior via differences in neural processes during safe decision-making. A total of 77 adolescents (range = 12–15 years, M<sub>age</sub> = 13.45 years, 40 females) completed a computerized driving task during a functional MRI scan. Results showed that adolescents’ perceptions of sibling closeness were associated with greater neural activation in the anterior insula, ventral striatum and left ventrolateral prefrontal cortex when making safe decisions, suggesting that the quality of sibling relationships modulates adolescent neurocognition even without being present. Furthermore, moderated mediation analyses revealed that higher sibling closeness was associated with lower externalizing behavior via left anterior insula activation during safe decision-making, but only for adolescents without older siblings (i.e. eldest children) compared to adolescents who had multiple older siblings. Importantly, these findings persisted above and beyond parental and peer closeness and sibling characteristics (i.e. sex, relatedness, birth order), highlighting the significant influence of sibling relationships on adolescent externalizing behavior through the brain.

**Citation:** Rogers, C. R., McCormick, E. M., van Hoorn, J., Ivory, S., & Telzer, E. H. (2018). Neural correlates of sibling closeness and association with externalizing behavior in adolescence. *Social Cognitive and Affective Neuroscience, 13*, 977–988.