---
title: "Adolescent neurodevelopment of cognitive control and risk-taking in negative family contexts."
output:
  distill::distill_article:
    css: ../../../styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[<i class="fas fa-file-download"></i> PDF](static/pubs/01-2016-NeuroImage/1.McCormick-Qu-Telzer-2016-NeuroImage.pdf) | [<i class="fas fa-quote-left"></i><i class="fas fa-quote-right"></i> BibTeX Citation](static/pubs/01-2016-NeuroImage/cite.bib)  | [<i class="ai ai-open-data"></i> Dataset](https://neurovault.org/collections/1827/)| [<i class="fas fa-link"></i> DOI](https://doi.org/10.1016/j.neuroimage.2015.09.063)

### Abstract
Adolescents have an increased need to regulate their behavior as they gain access to opportunities for risky behavior; however, cognitive control systems necessary for this regulation remain relatively immature. Parents can impact their adolescent child's abilities to regulate their behavior and engagement in risk taking. Since adolescents undergo significant neural change, negative parent–child relationship quality may impede or alter development in prefrontal regions subserving cognitive control. To test this hypothesis, 20 adolescents completed a Go/NoGo task during two fMRI scans occurring 1 year apart. Adolescents reporting greater family conflict and lower family cohesion showed longitudinal increases in risk-taking behavior, which was mediated by longitudinal increases in left VLPFC activation during cognitive control. These results underscore the importance of parent–child relationships during early adolescence, and the neural processes by which cognitive control may be derailed and may lead to increased risk taking.

**Citation:** McCormick, E. M., Qu, Y., & Telzer, E. H. (2016). Adolescent neurodevelopment of cognitive control and risk-taking in negative family contexts. *NeuroImage, 124*, 989-996.