---
title: "Moderate social sensitivity in a risky context supports adaptive decision-making in adolescence: Evidence from brain and behavior."
output:
  distill::distill_article:
    css: ../../../styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[<i class="fas fa-file-download"></i> PDF](9.van-Hoorn-McCormick-Telzer-2018-SCAN.pdf) | [<i class="fas fa-quote-left"></i><i class="fas fa-quote-right"></i> BibTeX Citation](cite.bib) | [<i class="fas fa-link"></i> DOI](https://doi.org/10.1093/scan/nsy016)

### Abstract
Adolescence is a time of increased social-affective sensitivity, which is often related to heightened health-risk behaviors. However, moderate levels of social sensitivity, relative to either low (social vacuum) or high levels (exceptionally attuned), may confer benefits as it facilitates effective navigation of the social world. The present fMRI study tested a curvilinear relationship between social sensitivity and adaptive decision-making. Participants (ages 12–16; N = 35) played the Social Analogue Risk Task, which measures participants’ willingness to knock on doors in order to earn points. With each knock, the facial expression of the house’s resident shifted from happy to somewhat angrier. If the resident became too angry, the door slammed and participants lost points. Social sensitivity was defined as the extent to which adolescents adjusted their risky choices based on shifting facial expressions. Results confirmed a curvilinear relationship between social sensitivity and self-reported adaptive decision-making at the behavioral and neural level. Moderate adolescent social sensitivity was modulated via heightened tracking of social cues in the temporoparietal junction, insula and dorsolateral prefrontal cortex and related to adaptive decision-making. These findings suggest that social-affective sensitivity may positively impact outcomes in adolescence and have implications for interventions to help adolescents reach mature social goals into adulthood.

**Citation:** van Hoorn, J., McCormick, E. M., & Telzer, E. H. (2018). Moderate social sensitivity in a risky context supports adaptive decision-making in adolescence: Evidence from brain and behavior. *Social Cognitive and Affective Neuroscience, 13*(5), 546–556.