<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Nested Data | The Hitchhiker’s Guide to Longitudinal Models</title>
  <meta name="description" content="This is a code companion for The Hitchhiker’s Guide to Longitudinal Models." />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Nested Data | The Hitchhiker’s Guide to Longitudinal Models" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a code companion for The Hitchhiker’s Guide to Longitudinal Models." />
  <meta name="github-repo" content="McCormickNeuro/longitudinal-primer" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Nested Data | The Hitchhiker’s Guide to Longitudinal Models" />
  
  <meta name="twitter:description" content="This is a code companion for The Hitchhiker’s Guide to Longitudinal Models." />
  

<meta name="author" content="Ethan M. McCormick, Michelle L. Byrne, John C. Flournoy, Kathryn L. Mills, &amp; Jennifer H. Pfiefer" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="05-covariates.html"/>
<link rel="next" href="07-datasets.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/font-awesome-5.13.0/js/script.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">The Hitchhiker’s Guide to Longitudinal Models</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="" data-path="01-introduction.html"><a href="01-introduction.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html"><i class="fa fa-check"></i>Canonical Models</a>
<ul>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#multilevel-model"><i class="fa fa-check"></i>Multilevel Model</a>
<ul>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#nlme"><i class="fa fa-check"></i>nlme</a></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#lme4"><i class="fa fa-check"></i>lme4</a></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#lmertest"><i class="fa fa-check"></i>lmerTest</a></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#mlm-outputs"><i class="fa fa-check"></i>MLM Outputs</a></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#mlm-plotting-model-implied-trajectories"><i class="fa fa-check"></i>MLM Plotting Model-Implied Trajectories</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#generalized-additive-mixed-model"><i class="fa fa-check"></i>Generalized Additive Mixed Model</a>
<ul>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#gamm-outputs"><i class="fa fa-check"></i>GAMM Outputs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#latent-curve-model"><i class="fa fa-check"></i>Latent Curve Model</a>
<ul>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#lcm-syntax-and-model-fitting"><i class="fa fa-check"></i>LCM Syntax and Model Fitting</a></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#lcm-outputs"><i class="fa fa-check"></i>LCM Outputs</a></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#lcm-path-diagrams"><i class="fa fa-check"></i>LCM Path Diagrams</a></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#lcm-plotting-model-implied-trajectories"><i class="fa fa-check"></i>LCM Plotting Model-Implied Trajectories</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#latent-change-score-model"><i class="fa fa-check"></i>Latent Change Score Model</a>
<ul>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#linear-lcsm"><i class="fa fa-check"></i>Linear LCSM</a></li>
<li class="chapter" data-level="" data-path="02-canonical.html"><a href="02-canonical.html#linear-lcsm-with-proportional-change"><i class="fa fa-check"></i>Linear LCSM with Proportional Change</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="03-time.html"><a href="03-time.html"><i class="fa fa-check"></i>Time Structure</a>
<ul>
<li class="chapter" data-level="" data-path="03-time.html"><a href="03-time.html#assessment-schedules"><i class="fa fa-check"></i>Assessment Schedules</a>
<ul>
<li class="chapter" data-level="" data-path="03-time.html"><a href="03-time.html#single-cohort-data"><i class="fa fa-check"></i>Single Cohort Data</a></li>
<li class="chapter" data-level="" data-path="03-time.html"><a href="03-time.html#multiple-cohort-data"><i class="fa fa-check"></i>Multiple Cohort Data</a></li>
<li class="chapter" data-level="" data-path="03-time.html"><a href="03-time.html#accelerated-design"><i class="fa fa-check"></i>Accelerated Design</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="03-time.html"><a href="03-time.html#time-coding"><i class="fa fa-check"></i>Time Coding</a></li>
<li class="chapter" data-level="" data-path="03-time.html"><a href="03-time.html#additional-considerations"><i class="fa fa-check"></i>Additional Considerations</a>
<ul>
<li class="chapter" data-level="" data-path="03-time.html"><a href="03-time.html#alternative-metrics-of-time"><i class="fa fa-check"></i>Alternative Metrics of Time</a></li>
<li class="chapter" data-level="" data-path="03-time.html"><a href="03-time.html#residual-estimates"><i class="fa fa-check"></i>Residual Estimates</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="04-shape.html"><a href="04-shape.html"><i class="fa fa-check"></i>The Shape of Development</a>
<ul>
<li class="chapter" data-level="" data-path="04-shape.html"><a href="04-shape.html#polynomial-trajectories"><i class="fa fa-check"></i>Polynomial Trajectories</a>
<ul>
<li class="chapter" data-level="" data-path="04-shape.html"><a href="04-shape.html#intercept-only-model"><i class="fa fa-check"></i>Intercept-Only Model</a></li>
<li class="chapter" data-level="" data-path="04-shape.html"><a href="04-shape.html#linear-model"><i class="fa fa-check"></i>Linear Model</a></li>
<li class="chapter" data-level="" data-path="04-shape.html"><a href="04-shape.html#quadratic-model"><i class="fa fa-check"></i>Quadratic Model</a></li>
<li class="chapter" data-level="" data-path="04-shape.html"><a href="04-shape.html#inverse-model"><i class="fa fa-check"></i>Inverse Model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="04-shape.html"><a href="04-shape.html#piecewise-trajectories"><i class="fa fa-check"></i>Piecewise Trajectories</a></li>
<li class="chapter" data-level="" data-path="04-shape.html"><a href="04-shape.html#nonlinear-trajectories"><i class="fa fa-check"></i>Nonlinear Trajectories</a></li>
<li class="chapter" data-level="" data-path="04-shape.html"><a href="04-shape.html#fixed-and-random-effects"><i class="fa fa-check"></i>Fixed and Random Effects</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="05-covariates.html"><a href="05-covariates.html"><i class="fa fa-check"></i>Covariates and Distal Outcomes</a>
<ul>
<li class="chapter" data-level="" data-path="05-covariates.html"><a href="05-covariates.html#covariates-1"><i class="fa fa-check"></i>Covariates</a>
<ul>
<li class="chapter" data-level="" data-path="05-covariates.html"><a href="05-covariates.html#time-invariant-covariates"><i class="fa fa-check"></i>Time Invariant Covariates</a></li>
<li class="chapter" data-level="" data-path="05-covariates.html"><a href="05-covariates.html#cross-level-interactions"><i class="fa fa-check"></i>Cross-Level Interactions</a></li>
<li class="chapter" data-level="" data-path="05-covariates.html"><a href="05-covariates.html#time-varying-covariates"><i class="fa fa-check"></i>Time Varying Covariates</a></li>
<li class="chapter" data-level="" data-path="05-covariates.html"><a href="05-covariates.html#multivariate-models"><i class="fa fa-check"></i>Multivariate Models</a></li>
<li class="chapter" data-level="" data-path="05-covariates.html"><a href="05-covariates.html#within--and-betwen-person-variance"><i class="fa fa-check"></i>Within- and Betwen-Person Variance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="05-covariates.html"><a href="05-covariates.html#distal-outcomes"><i class="fa fa-check"></i>Distal Outcomes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="06-nesting.html"><a href="06-nesting.html"><i class="fa fa-check"></i>Nested Data</a>
<ul>
<li class="chapter" data-level="" data-path="06-nesting.html"><a href="06-nesting.html#unconditional-model"><i class="fa fa-check"></i>Unconditional Model</a></li>
<li class="chapter" data-level="" data-path="06-nesting.html"><a href="06-nesting.html#categorical-predictors"><i class="fa fa-check"></i>Categorical Predictors</a></li>
<li class="chapter" data-level="" data-path="06-nesting.html"><a href="06-nesting.html#multiple-groups-models"><i class="fa fa-check"></i>Multiple Groups Models</a></li>
<li class="chapter" data-level="" data-path="06-nesting.html"><a href="06-nesting.html#fixed-effect-approach"><i class="fa fa-check"></i>Fixed Effect Approach</a></li>
<li class="chapter" data-level="" data-path="06-nesting.html"><a href="06-nesting.html#random-effect-approach"><i class="fa fa-check"></i>Random Effect Approach</a></li>
<li class="chapter" data-level="" data-path="06-nesting.html"><a href="06-nesting.html#cluster-correction"><i class="fa fa-check"></i>Cluster Correction</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="07-datasets.html"><a href="07-datasets.html"><i class="fa fa-check"></i>Datasets</a>
<ul>
<li class="chapter" data-level="" data-path="07-datasets.html"><a href="07-datasets.html#descriptions"><i class="fa fa-check"></i>Descriptions</a>
<ul>
<li class="chapter" data-level="" data-path="07-datasets.html"><a href="07-datasets.html#executive-function"><i class="fa fa-check"></i>Executive Function</a></li>
<li class="chapter" data-level="" data-path="07-datasets.html"><a href="07-datasets.html#feedback-learning"><i class="fa fa-check"></i>Feedback Learning</a></li>
<li class="chapter" data-level="" data-path="07-datasets.html"><a href="07-datasets.html#externalizing-and-math"><i class="fa fa-check"></i>Externalizing and Math</a></li>
<li class="chapter" data-level="" data-path="07-datasets.html"><a href="07-datasets.html#adversity"><i class="fa fa-check"></i>Adversity</a></li>
<li class="chapter" data-level="" data-path="07-datasets.html"><a href="07-datasets.html#trials"><i class="fa fa-check"></i>Trials</a></li>
<li class="chapter" data-level="" data-path="07-datasets.html"><a href="07-datasets.html#achieve"><i class="fa fa-check"></i>Achieve</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The Hitchhiker’s Guide to Longitudinal Models</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="nesting" class="section level1 hasAnchor">
<h1>Nested Data<a href="06-nesting.html#nesting" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The final topic we will consider is the way we account for nesting within longitudinal data. While technically all of longitudinal modeling involves nested data (i.e., multiple observations nested within the same individual), here we focus more on between-person nesting groups (e.g., classroom, family, data collection sites). As we will see, there are several forms of the models that we have already used that deal with nesting. The <code>achieve</code> dataset we will work with here are from a 4-wave school-based assessment of math and science achievement across ages <span class="math inline">\(12\)</span> - <span class="math inline">\(17\)</span>. Schools were drawn from <span class="math inline">\(5\)</span> different metropolitan areas and assessments were conducted by separate research teams in each city. Here we will mostly focus on the science achievement data, but may draw examples from math achievement if they differ in interesting ways.</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="06-nesting.html#cb257-1" aria-hidden="true" tabindex="-1"></a>achieve <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/achieve.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb257-2"><a href="06-nesting.html#cb257-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-3"><a href="06-nesting.html#cb257-3" aria-hidden="true" tabindex="-1"></a>achieve.wide <span class="ot">&lt;-</span> achieve <span class="sc">%&gt;%</span></span>
<span id="cb257-4"><a href="06-nesting.html#cb257-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> <span class="fu">c</span>(<span class="st">&quot;site&quot;</span>, <span class="st">&quot;school&quot;</span>, <span class="st">&quot;id&quot;</span>, <span class="st">&quot;male&quot;</span>), </span>
<span id="cb257-5"><a href="06-nesting.html#cb257-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">names_from =</span> <span class="st">&quot;wave&quot;</span>,</span>
<span id="cb257-6"><a href="06-nesting.html#cb257-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> <span class="fu">c</span>(<span class="st">&quot;sci&quot;</span>, <span class="st">&quot;math&quot;</span>),</span>
<span id="cb257-7"><a href="06-nesting.html#cb257-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">names_sep =</span> <span class="st">&quot;.&quot;</span>,</span>
<span id="cb257-8"><a href="06-nesting.html#cb257-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_fill =</span> <span class="cn">NA</span>)</span></code></pre></div>
<p>As always, we can fit an unconditional growth model to give us a baseline of expectations for the effects we will in subsequent models. Here we will fit the MLM and LCM versions as they are the simplest representations.</p>
<div id="unconditional-model" class="section level2 hasAnchor">
<h2>Unconditional Model<a href="06-nesting.html#unconditional-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="06-nesting.html#cb258-1" aria-hidden="true" tabindex="-1"></a>unc.mlm <span class="ot">&lt;-</span> <span class="fu">lmer</span>(sci <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">|</span> id),</span>
<span id="cb258-2"><a href="06-nesting.html#cb258-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action =</span> na.omit,</span>
<span id="cb258-3"><a href="06-nesting.html#cb258-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">REML =</span> <span class="cn">TRUE</span>,</span>
<span id="cb258-4"><a href="06-nesting.html#cb258-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> achieve)</span>
<span id="cb258-5"><a href="06-nesting.html#cb258-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb258-6"><a href="06-nesting.html#cb258-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(unc.mlm, <span class="at">correlation =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sci ~ 1 + wave + (1 + wave | id)
##    Data: achieve
## 
## REML criterion at convergence: 24100
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.5673 -0.4152  0.0084  0.4532  4.2100 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  id       (Intercept) 94.998   9.747         
##           wave         4.035   2.009    -0.09
##  Residual             12.367   3.517         
## Number of obs: 3643, groups:  id, 1200
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept) 5.881e+01  3.180e-01 1.133e+03   185.0   &lt;2e-16 ***
## wave        1.987e+00  8.716e-02 8.628e+02    22.8   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="06-nesting.html#cb260-1" aria-hidden="true" tabindex="-1"></a>unc.lcm <span class="ot">&lt;-</span> <span class="st">&quot;int =~ 1*sci.1 + 1*sci.2 + 1*sci.3 + 1*sci.4</span></span>
<span id="cb260-2"><a href="06-nesting.html#cb260-2" aria-hidden="true" tabindex="-1"></a><span class="st">            slp =~ 0*sci.1 + 1*sci.2 + 2*sci.3 + 3*sci.4&quot;</span></span>
<span id="cb260-3"><a href="06-nesting.html#cb260-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb260-4"><a href="06-nesting.html#cb260-4" aria-hidden="true" tabindex="-1"></a>unc.lcm.fit <span class="ot">&lt;-</span> <span class="fu">growth</span>(unc.lcm,</span>
<span id="cb260-5"><a href="06-nesting.html#cb260-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> achieve.wide,</span>
<span id="cb260-6"><a href="06-nesting.html#cb260-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">estimator =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb260-7"><a href="06-nesting.html#cb260-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">missing =</span> <span class="st">&quot;FIML&quot;</span>)</span>
<span id="cb260-8"><a href="06-nesting.html#cb260-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb260-9"><a href="06-nesting.html#cb260-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(unc.lcm.fit, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">estimates =</span> <span class="cn">TRUE</span>, </span>
<span id="cb260-10"><a href="06-nesting.html#cb260-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">standardize =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-10 ended normally after 147 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                         9
##                                                       
##                                                   Used       Total
##   Number of observations                          1200        1237
##   Number of missing patterns                        15            
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                                55.402
##   Degrees of freedom                                 5
##   P-value (Chi-square)                           0.000
## 
## Model Test Baseline Model:
## 
##   Test statistic                              3806.133
##   Degrees of freedom                                 6
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.987
##   Tucker-Lewis Index (TLI)                       0.984
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)             -12038.652
##   Loglikelihood unrestricted model (H1)     -12010.951
##                                                       
##   Akaike (AIC)                               24095.304
##   Bayesian (BIC)                             24141.115
##   Sample-size adjusted Bayesian (BIC)        24112.527
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.092
##   90 Percent confidence interval - lower         0.071
##   90 Percent confidence interval - upper         0.114
##   P-value RMSEA &lt;= 0.05                          0.001
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.031
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Observed
##   Observed information based on                Hessian
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int =~                                                                
##     sci.1             1.000                               9.722    0.934
##     sci.2             1.000                               9.722    0.898
##     sci.3             1.000                               9.722    0.851
##     sci.4             1.000                               9.722    0.757
##   slp =~                                                                
##     sci.1             0.000                               0.000    0.000
##     sci.2             1.000                               1.910    0.176
##     sci.3             2.000                               3.820    0.334
##     sci.4             3.000                               5.730    0.446
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int ~~                                                                
##     slp               3.184    1.033    3.083    0.002    0.172    0.172
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1             0.000                               0.000    0.000
##    .sci.2             0.000                               0.000    0.000
##    .sci.3             0.000                               0.000    0.000
##    .sci.4             0.000                               0.000    0.000
##     int              60.782    0.299  203.517    0.000    6.252    6.252
##     slp               2.048    0.090   22.857    0.000    1.072    1.072
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1            13.812    1.437    9.610    0.000   13.812    0.128
##    .sci.2            12.641    0.948   13.341    0.000   12.641    0.108
##    .sci.3             8.580    0.950    9.028    0.000    8.580    0.066
##    .sci.4            18.517    1.984    9.331    0.000   18.517    0.112
##     int              94.510    4.430   21.333    0.000    1.000    1.000
##     slp               3.648    0.442    8.256    0.000    1.000    1.000
## 
## R-Square:
##                    Estimate
##     sci.1             0.872
##     sci.2             0.892
##     sci.3             0.934
##     sci.4             0.888</code></pre>
<p>As a general takeaway, we have an average science achievement of around <span class="math inline">\(60\)</span> (these scores are arbitrarily scaled so that isn’t incredibly informative) but more of interest, science achievement is increasing over time approximately <span class="math inline">\(2\)</span> points per year of school.</p>
</div>
<div id="categorical-predictors" class="section level2 hasAnchor">
<h2>Categorical Predictors<a href="06-nesting.html#categorical-predictors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Nesting induces correlations between observations because members of the same group are more similar to one another than members of other groups. The practical upshot of these models is that we obtain different values of parameters across group (although the methods for this will vary). Perhaps the simplest method for doing so, and therefore accounting for group differences, is to predict the mean of the outcome variable using a categorical predictor. In longitudinal modeling, this most often occurs at the level of the individual as a TIC. As such, we already know how to fit this kind of model from the last chapter. We can show this syntax again below. Here we predict the intercept and slope random effects with <code>male</code> to examine differences between self-reported males and females. In the MLM syntax, we simply include <code>male</code> in the regression equation if we want to predict mean differences in science achievement.</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="06-nesting.html#cb262-1" aria-hidden="true" tabindex="-1"></a>cat.mlm<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lmer</span>(sci <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">+</span> male <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">|</span> id),</span>
<span id="cb262-2"><a href="06-nesting.html#cb262-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action =</span> na.omit,</span>
<span id="cb262-3"><a href="06-nesting.html#cb262-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">REML =</span> <span class="cn">TRUE</span>,</span>
<span id="cb262-4"><a href="06-nesting.html#cb262-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> achieve)</span>
<span id="cb262-5"><a href="06-nesting.html#cb262-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb262-6"><a href="06-nesting.html#cb262-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cat.mlm<span class="fl">.1</span>, <span class="at">correlation =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sci ~ 1 + wave + male + (1 + wave | id)
##    Data: achieve
## 
## REML criterion at convergence: 24092
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.5819 -0.4169  0.0084  0.4561  4.1991 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  id       (Intercept) 94.728   9.733         
##           wave         4.041   2.010    -0.09
##  Residual             12.364   3.516         
## Number of obs: 3643, groups:  id, 1200
## 
## Fixed effects:
##              Estimate Std. Error        df t value Pr(&gt;|t|)    
## (Intercept)   58.0466     0.4255 1235.3628 136.425  &lt; 2e-16 ***
## wave           1.9866     0.0872  862.4359  22.783  &lt; 2e-16 ***
## male           1.5965     0.5918 1190.5963   2.698  0.00708 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Here we see that males show <span class="math inline">\(1.6\)</span> units higher science achievement compared with females (the reference category). It is possible to predict other parameters in the model, although the options in mixed-effects models tend to be more limited compared with SEM approaches. For instance, if we thought error variance might differ across groups, we could include this in our MLM syntax through the variance identity (<code>varIdent</code>) function. The <code>form</code> equation, <code>~ 1 | male</code>, mimics the regression equation where we have a separate “intercept” (here just read this as estimate) nested within group (<code>male</code>). We can then go through the procedure we covered in Chapter 3 to recover the different estimates for males and females (here in standard deviations, but we can easily square these values to obtain variances).</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="06-nesting.html#cb264-1" aria-hidden="true" tabindex="-1"></a>cat.mlm<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lme</span>(sci <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">+</span> male,</span>
<span id="cb264-2"><a href="06-nesting.html#cb264-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">|</span> id,</span>
<span id="cb264-3"><a href="06-nesting.html#cb264-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> male),</span>
<span id="cb264-4"><a href="06-nesting.html#cb264-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">na.action =</span> na.omit,</span>
<span id="cb264-5"><a href="06-nesting.html#cb264-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">method =</span> <span class="st">&quot;REML&quot;</span>,</span>
<span id="cb264-6"><a href="06-nesting.html#cb264-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> achieve)</span>
<span id="cb264-7"><a href="06-nesting.html#cb264-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb264-8"><a href="06-nesting.html#cb264-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cat.mlm<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: achieve 
##        AIC      BIC    logLik
##   24090.94 24140.54 -12037.47
## 
## Random effects:
##  Formula: ~1 + wave | id
##  Structure: General positive-definite, Log-Cholesky parametrization
##             StdDev   Corr  
## (Intercept) 9.705309 (Intr)
## wave        2.004751 -0.091
## Residual    3.278687       
## 
## Variance function:
##  Structure: Different standard deviations per stratum
##  Formula: ~1 | male 
##  Parameter estimates:
##        0        1 
## 1.000000 1.153432 
## Fixed effects:  sci ~ 1 + wave + male 
##                Value Std.Error   DF   t-value p-value
## (Intercept) 58.06283 0.4214427 2442 137.77158  0.0000
## wave         1.97570 0.0869694 2442  22.71723  0.0000
## male         1.60921 0.5911793 1198   2.72203  0.0066
##  Correlation: 
##      (Intr) wave  
## wave -0.260       
## male -0.660 -0.019
## 
## Standardized Within-Group Residuals:
##          Min           Q1          Med           Q3          Max 
## -4.357804935 -0.422607606  0.007362749  0.463816949  3.998105364 
## 
## Number of Observations: 3643
## Number of Groups: 1200</code></pre>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="06-nesting.html#cb266-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(cat.mlm<span class="fl">.2</span><span class="sc">$</span>sigma, cat.mlm<span class="fl">.2</span><span class="sc">$</span>sigma <span class="sc">*</span> <span class="fu">exp</span>(<span class="fu">as.numeric</span>(cat.mlm<span class="fl">.2</span><span class="sc">$</span>modelStruct<span class="sc">$</span>varStruct)))</span></code></pre></div>
<pre><code>## [1] 3.278687 3.781742</code></pre>
<p>These results show that males appear to have increased variability in their science achievement compared to females in addition to a higher average. Note that we are not getting a direct effect estimate here, but rather estimating values separately for each group. There are not clear ways of implementing that kind of effect in <strong>lme4</strong>, so we will not go too much further except to mention that within the mixed-effect world of models, you can directly model predictors of variability with location-scale models, although those generally require more intensive longitudinal kinds of data. As such, we will not consider this further.</p>
<p>Because these categorical variables enter the model at the person level, in the mixed-effects models they predict the random effects rather than the individual time-specific observations. However, in the SEM, we can additionally predict one (or more) of the individual repeated measures. We can see this approach in a version of a MIMIC model, where we predict both the latent factors and the first repeated measure (<code>sci.1</code>).</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="06-nesting.html#cb268-1" aria-hidden="true" tabindex="-1"></a>cat.lcm <span class="ot">&lt;-</span> <span class="st">&quot;int =~ 1*sci.1 + 1*sci.2 + 1*sci.3 + 1*sci.4</span></span>
<span id="cb268-2"><a href="06-nesting.html#cb268-2" aria-hidden="true" tabindex="-1"></a><span class="st">            slp =~ 0*sci.1 + 1*sci.2 + 2*sci.3 + 3*sci.4</span></span>
<span id="cb268-3"><a href="06-nesting.html#cb268-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb268-4"><a href="06-nesting.html#cb268-4" aria-hidden="true" tabindex="-1"></a><span class="st">            int ~ male</span></span>
<span id="cb268-5"><a href="06-nesting.html#cb268-5" aria-hidden="true" tabindex="-1"></a><span class="st">            slp ~ male</span></span>
<span id="cb268-6"><a href="06-nesting.html#cb268-6" aria-hidden="true" tabindex="-1"></a><span class="st">            </span></span>
<span id="cb268-7"><a href="06-nesting.html#cb268-7" aria-hidden="true" tabindex="-1"></a><span class="st">            sci.1 ~ male&quot;</span></span>
<span id="cb268-8"><a href="06-nesting.html#cb268-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb268-9"><a href="06-nesting.html#cb268-9" aria-hidden="true" tabindex="-1"></a>cat.lcm.fit <span class="ot">&lt;-</span> <span class="fu">growth</span>(cat.lcm,</span>
<span id="cb268-10"><a href="06-nesting.html#cb268-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> achieve.wide,</span>
<span id="cb268-11"><a href="06-nesting.html#cb268-11" aria-hidden="true" tabindex="-1"></a>                      <span class="at">estimator =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb268-12"><a href="06-nesting.html#cb268-12" aria-hidden="true" tabindex="-1"></a>                      <span class="at">missing =</span> <span class="st">&quot;FIML&quot;</span>)</span>
<span id="cb268-13"><a href="06-nesting.html#cb268-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb268-14"><a href="06-nesting.html#cb268-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cat.lcm.fit, <span class="at">fit.measures =</span> <span class="cn">FALSE</span>, <span class="at">estimates =</span> <span class="cn">TRUE</span>, </span>
<span id="cb268-15"><a href="06-nesting.html#cb268-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">standardize =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-10 ended normally after 143 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        12
##                                                       
##   Number of observations                          1237
##   Number of missing patterns                        16
##                                                       
## Model Test User Model:
##                                                       
##   Test statistic                                37.324
##   Degrees of freedom                                 6
##   P-value (Chi-square)                           0.000
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Observed
##   Observed information based on                Hessian
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int =~                                                                
##     sci.1             1.000                               9.812    0.944
##     sci.2             1.000                               9.812    0.904
##     sci.3             1.000                               9.812    0.859
##     sci.4             1.000                               9.812    0.768
##   slp =~                                                                
##     sci.1             0.000                               0.000    0.000
##     sci.2             1.000                               1.941    0.179
##     sci.3             2.000                               3.883    0.340
##     sci.4             3.000                               5.824    0.456
## 
## Regressions:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int ~                                                                 
##     male              2.659    0.649    4.095    0.000    0.271    0.135
##   slp ~                                                                 
##     male             -0.288    0.217   -1.324    0.186   -0.148   -0.074
##   sci.1 ~                                                               
##     male             -1.511    0.336   -4.503    0.000   -1.511   -0.073
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##  .int ~~                                                                
##    .slp               2.789    1.036    2.693    0.007    0.148    0.148
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1             0.000                               0.000    0.000
##    .sci.2             0.000                               0.000    0.000
##    .sci.3             0.000                               0.000    0.000
##    .sci.4             0.000                               0.000    0.000
##    .int              60.057    0.412  145.793    0.000    6.121    6.121
##    .slp               1.907    0.121   15.788    0.000    0.982    0.982
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1            13.139    1.423    9.234    0.000   13.139    0.122
##    .sci.2            12.579    0.946   13.301    0.000   12.579    0.107
##    .sci.3             8.827    0.954    9.255    0.000    8.827    0.068
##    .sci.4            17.512    1.947    8.994    0.000   17.512    0.107
##    .int              94.515    4.423   21.370    0.000    0.982    0.982
##    .slp               3.749    0.440    8.517    0.000    0.995    0.995</code></pre>
<p>These approaches are relatively simple ways to incorporate nesting information into the model, but highlight the continuity with more complex approaches we will discuss as we move forward in this chapter.</p>
</div>
<div id="multiple-groups-models" class="section level2 hasAnchor">
<h2>Multiple Groups Models<a href="06-nesting.html#multiple-groups-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>While the categorical predictor allows us to vary some parameters across groups, a unique power of the SEM is the multiple group model, where we can estimate unique parameters of essentially any type across any number of groups (although the number of groups tends to be small in practice). The reason for a small number of groups tends to be due to sample size requirements within-group. SEM is still a large-sample estimator in the multiple groups model, so we have to be careful we aren’t under-powering the model at the group level, even if the overall sample size is large. Below we can see how the multiple-group LCM is specified. Nothing changes about the syntax object <code>mult.g1</code> from what we have seen before, however, now we include the argument <code>group = "male"</code> to indicate that we want to obtain unique estimates for females and males. Typically, these models require setting some small set of parameters equal in the model just to identify the model, so here we conveniently achieve this through having the same set factor loadings for the growth model. We can see the results below.</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="06-nesting.html#cb270-1" aria-hidden="true" tabindex="-1"></a>mult.g1 <span class="ot">&lt;-</span> <span class="st">&quot;int =~ 1*sci.1 + 1*sci.2 + 1*sci.3 + 1*sci.4</span></span>
<span id="cb270-2"><a href="06-nesting.html#cb270-2" aria-hidden="true" tabindex="-1"></a><span class="st">            slp =~ 0*sci.1 + 1*sci.2 + 2*sci.3 + 3*sci.4&quot;</span></span>
<span id="cb270-3"><a href="06-nesting.html#cb270-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb270-4"><a href="06-nesting.html#cb270-4" aria-hidden="true" tabindex="-1"></a>mult.g1.fit <span class="ot">&lt;-</span> <span class="fu">growth</span>(mult.g1,</span>
<span id="cb270-5"><a href="06-nesting.html#cb270-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> achieve.wide,</span>
<span id="cb270-6"><a href="06-nesting.html#cb270-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">group =</span> <span class="st">&quot;male&quot;</span>,</span>
<span id="cb270-7"><a href="06-nesting.html#cb270-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">estimator =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb270-8"><a href="06-nesting.html#cb270-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">missing =</span> <span class="st">&quot;FIML&quot;</span>)</span>
<span id="cb270-9"><a href="06-nesting.html#cb270-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb270-10"><a href="06-nesting.html#cb270-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mult.g1.fit, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">estimates =</span> <span class="cn">TRUE</span>, </span>
<span id="cb270-11"><a href="06-nesting.html#cb270-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">standardize =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-10 ended normally after 222 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        18
##                                                       
##   Number of observations per group:               Used       Total
##     1                                              576         600
##     0                                              624         637
##   Number of missing patterns per group:                           
##     1                                               15            
##     0                                               15            
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                                61.451
##   Degrees of freedom                                10
##   P-value (Chi-square)                           0.000
##   Test statistic for each group:
##     1                                           30.756
##     0                                           30.695
## 
## Model Test Baseline Model:
## 
##   Test statistic                              3772.258
##   Degrees of freedom                                12
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.986
##   Tucker-Lewis Index (TLI)                       0.984
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)             -12013.745
##   Loglikelihood unrestricted model (H1)     -11983.019
##                                                       
##   Akaike (AIC)                               24063.489
##   Bayesian (BIC)                             24155.111
##   Sample-size adjusted Bayesian (BIC)        24097.936
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.093
##   90 Percent confidence interval - lower         0.071
##   90 Percent confidence interval - upper         0.115
##   P-value RMSEA &lt;= 0.05                          0.001
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.036
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Observed
##   Observed information based on                Hessian
## 
## 
## Group 1 [1]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int =~                                                                
##     sci.1             1.000                              10.624    0.933
##     sci.2             1.000                              10.624    0.903
##     sci.3             1.000                              10.624    0.859
##     sci.4             1.000                              10.624    0.765
##   slp =~                                                                
##     sci.1             0.000                               0.000    0.000
##     sci.2             1.000                               1.824    0.155
##     sci.3             2.000                               3.648    0.295
##     sci.4             3.000                               5.472    0.394
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int ~~                                                                
##     slp               4.373    1.704    2.567    0.010    0.226    0.226
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1             0.000                               0.000    0.000
##    .sci.2             0.000                               0.000    0.000
##    .sci.3             0.000                               0.000    0.000
##    .sci.4             0.000                               0.000    0.000
##     int              61.564    0.472  130.490    0.000    5.795    5.795
##     slp               2.217    0.136   16.342    0.000    1.216    1.216
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1            16.927    2.377    7.121    0.000   16.927    0.130
##    .sci.2            13.629    1.534    8.882    0.000   13.629    0.098
##    .sci.3             9.128    1.557    5.861    0.000    9.128    0.060
##    .sci.4            24.031    3.370    7.131    0.000   24.031    0.124
##     int             112.875    7.647   14.760    0.000    1.000    1.000
##     slp               3.327    0.713    4.665    0.000    1.000    1.000
## 
## 
## Group 2 [0]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int =~                                                                
##     sci.1             1.000                               8.752    0.936
##     sci.2             1.000                               8.752    0.894
##     sci.3             1.000                               8.752    0.844
##     sci.4             1.000                               8.752    0.750
##   slp =~                                                                
##     sci.1             0.000                               0.000    0.000
##     sci.2             1.000                               1.967    0.201
##     sci.3             2.000                               3.934    0.379
##     sci.4             3.000                               5.901    0.506
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int ~~                                                                
##     slp               1.811    1.234    1.467    0.142    0.105    0.105
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1             0.000                               0.000    0.000
##    .sci.2             0.000                               0.000    0.000
##    .sci.3             0.000                               0.000    0.000
##    .sci.4             0.000                               0.000    0.000
##     int              60.051    0.372  161.225    0.000    6.861    6.861
##     slp               1.902    0.118   16.087    0.000    0.967    0.967
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1            10.906    1.731    6.301    0.000   10.906    0.125
##    .sci.2            11.783    1.175   10.028    0.000   11.783    0.123
##    .sci.3             8.222    1.177    6.984    0.000    8.222    0.076
##    .sci.4            13.792    2.349    5.870    0.000   13.792    0.101
##     int              76.605    4.979   15.386    0.000    1.000    1.000
##     slp               3.870    0.547    7.069    0.000    1.000    1.000</code></pre>
<p>We can see that we now have separate test statistics and sample sizes that reflect the fact that we are - to a large extent - estimating separate models. We also can see that our parameter estimates are broken up into <code>Group 1 [1]</code> and <code>Group 2 [0]</code>. The value in brackets represents the value of the grouping variable <code>male</code>, so here Group 1 is males and Group 2 is female (you could change this variable into a labeled factor and then those labels would be more informative). It’s important to note the ordering of the groups for future steps.</p>
<p>Here we can qualitatively say that among other things, males seem to start higher (<span class="math inline">\(61.6\)</span> vs. <span class="math inline">\(60.1\)</span>) and increase more rapidly (<span class="math inline">\(2.22\)</span> vs. <span class="math inline">\(1.90\)</span>) in their achievement, and have a higher correlation between starting point and rate of change (<span class="math inline">\(r = 0.226\)</span> vs. <span class="math inline">\(r = .105\)</span>), compared with females. However, a natural question is whether these differences are significant. We can explicitly test differences across groups by introducing group-specific labels into our model syntax and building composite parameters where we get a formal inferential test on the difference. A really nice feature of maximum likelihood parameters is that linear operations on the parameter are themselves maximum likelihood parameters themselves. To achieve this, we simply pre-multiply a given parameter by a vector of labels (e.g., <code>c(Mi, Fi)</code>) and then define the composite parameter using the <code>:=</code> operator. Here we will test the difference between the intercept (<code>c(Mi, Fi)</code>) and slope factor means (<code>c(Ms, Fs)</code>), and the covariance between factors (<code>c(Mc, Fc)</code>). This is where keeping track of the group order becomes important so we don’t mis-label our parameters of interest and reverse our inference. The <code>D*</code> composite parameters are then created by simply subtracting <code>F*</code> from the <code>M*</code> parameters.</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="06-nesting.html#cb272-1" aria-hidden="true" tabindex="-1"></a>mult.g2 <span class="ot">&lt;-</span> <span class="st">&quot;int =~ 1*sci.1 + 1*sci.2 + 1*sci.3 + 1*sci.4</span></span>
<span id="cb272-2"><a href="06-nesting.html#cb272-2" aria-hidden="true" tabindex="-1"></a><span class="st">            slp =~ 0*sci.1 + 1*sci.2 + 2*sci.3 + 3*sci.4</span></span>
<span id="cb272-3"><a href="06-nesting.html#cb272-3" aria-hidden="true" tabindex="-1"></a><span class="st">            </span></span>
<span id="cb272-4"><a href="06-nesting.html#cb272-4" aria-hidden="true" tabindex="-1"></a><span class="st">            int ~ c(Mi, Fi)*1</span></span>
<span id="cb272-5"><a href="06-nesting.html#cb272-5" aria-hidden="true" tabindex="-1"></a><span class="st">            slp ~ c(Ms, Fs)*1</span></span>
<span id="cb272-6"><a href="06-nesting.html#cb272-6" aria-hidden="true" tabindex="-1"></a><span class="st">            </span></span>
<span id="cb272-7"><a href="06-nesting.html#cb272-7" aria-hidden="true" tabindex="-1"></a><span class="st">            int ~~ c(Mc, Fc)*slp</span></span>
<span id="cb272-8"><a href="06-nesting.html#cb272-8" aria-hidden="true" tabindex="-1"></a><span class="st">            </span></span>
<span id="cb272-9"><a href="06-nesting.html#cb272-9" aria-hidden="true" tabindex="-1"></a><span class="st">            Di := Mi - Fi</span></span>
<span id="cb272-10"><a href="06-nesting.html#cb272-10" aria-hidden="true" tabindex="-1"></a><span class="st">            Ds := Ms - Fs</span></span>
<span id="cb272-11"><a href="06-nesting.html#cb272-11" aria-hidden="true" tabindex="-1"></a><span class="st">            Dc := Mc - Fc&quot;</span></span>
<span id="cb272-12"><a href="06-nesting.html#cb272-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb272-13"><a href="06-nesting.html#cb272-13" aria-hidden="true" tabindex="-1"></a>mult.g2.fit <span class="ot">&lt;-</span> <span class="fu">growth</span>(mult.g2,</span>
<span id="cb272-14"><a href="06-nesting.html#cb272-14" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> achieve.wide,</span>
<span id="cb272-15"><a href="06-nesting.html#cb272-15" aria-hidden="true" tabindex="-1"></a>                      <span class="at">group =</span> <span class="st">&quot;male&quot;</span>,</span>
<span id="cb272-16"><a href="06-nesting.html#cb272-16" aria-hidden="true" tabindex="-1"></a>                      <span class="at">estimator =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb272-17"><a href="06-nesting.html#cb272-17" aria-hidden="true" tabindex="-1"></a>                      <span class="at">missing =</span> <span class="st">&quot;FIML&quot;</span>)</span>
<span id="cb272-18"><a href="06-nesting.html#cb272-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb272-19"><a href="06-nesting.html#cb272-19" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mult.g2.fit, <span class="at">fit.measures =</span> <span class="cn">FALSE</span>, <span class="at">estimates =</span> <span class="cn">TRUE</span>, </span>
<span id="cb272-20"><a href="06-nesting.html#cb272-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">standardize =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-10 ended normally after 224 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        18
##                                                       
##   Number of observations per group:               Used       Total
##     1                                              576         600
##     0                                              624         637
##   Number of missing patterns per group:                           
##     1                                               15            
##     0                                               15            
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                                61.451
##   Degrees of freedom                                10
##   P-value (Chi-square)                           0.000
##   Test statistic for each group:
##     1                                           30.756
##     0                                           30.695
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Observed
##   Observed information based on                Hessian
## 
## 
## Group 1 [1]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int =~                                                                
##     sci.1             1.000                              10.624    0.933
##     sci.2             1.000                              10.624    0.903
##     sci.3             1.000                              10.624    0.859
##     sci.4             1.000                              10.624    0.765
##   slp =~                                                                
##     sci.1             0.000                               0.000    0.000
##     sci.2             1.000                               1.824    0.155
##     sci.3             2.000                               3.648    0.295
##     sci.4             3.000                               5.472    0.394
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int ~~                                                                
##     slp       (Mc)    4.373    1.704    2.567    0.010    0.226    0.226
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##     int       (Mi)   61.564    0.472  130.490    0.000    5.795    5.795
##     slp       (Ms)    2.217    0.136   16.342    0.000    1.216    1.216
##    .sci.1             0.000                               0.000    0.000
##    .sci.2             0.000                               0.000    0.000
##    .sci.3             0.000                               0.000    0.000
##    .sci.4             0.000                               0.000    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1            16.927    2.377    7.121    0.000   16.927    0.130
##    .sci.2            13.629    1.534    8.882    0.000   13.629    0.098
##    .sci.3             9.128    1.557    5.861    0.000    9.128    0.060
##    .sci.4            24.031    3.370    7.131    0.000   24.031    0.124
##     int             112.875    7.647   14.760    0.000    1.000    1.000
##     slp               3.327    0.713    4.665    0.000    1.000    1.000
## 
## 
## Group 2 [0]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int =~                                                                
##     sci.1             1.000                               8.752    0.936
##     sci.2             1.000                               8.752    0.894
##     sci.3             1.000                               8.752    0.844
##     sci.4             1.000                               8.752    0.750
##   slp =~                                                                
##     sci.1             0.000                               0.000    0.000
##     sci.2             1.000                               1.967    0.201
##     sci.3             2.000                               3.934    0.379
##     sci.4             3.000                               5.901    0.506
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int ~~                                                                
##     slp       (Fc)    1.811    1.234    1.467    0.142    0.105    0.105
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##     int       (Fi)   60.051    0.372  161.225    0.000    6.861    6.861
##     slp       (Fs)    1.902    0.118   16.087    0.000    0.967    0.967
##    .sci.1             0.000                               0.000    0.000
##    .sci.2             0.000                               0.000    0.000
##    .sci.3             0.000                               0.000    0.000
##    .sci.4             0.000                               0.000    0.000
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1            10.906    1.731    6.301    0.000   10.906    0.125
##    .sci.2            11.783    1.175   10.028    0.000   11.783    0.123
##    .sci.3             8.222    1.177    6.984    0.000    8.222    0.076
##    .sci.4            13.792    2.349    5.870    0.000   13.792    0.101
##     int              76.605    4.979   15.386    0.000    1.000    1.000
##     slp               3.870    0.547    7.069    0.000    1.000    1.000
## 
## Defined Parameters:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##     Di                1.513    0.601    2.517    0.012   -1.066   -1.066
##     Ds                0.316    0.180    1.753    0.080    0.249    0.249
##     Dc                2.562    2.104    1.217    0.223    0.120    0.120</code></pre>
<p>We will only focus here on the <code>Defined Parameters</code> section, where we can see that while males have higher absolute estimates on all of these parameters we have tested, only the mean of the intercept factor significantly differs across groups. These are only a subset we chose for demonstration purposes, and we could explore others if we chose.</p>
<p>However, this model allows maximally different estimates, which belies one of the real strengths of the multiple-groups model, which is to selectively set a subset of parameters equal across groups. This allows us to bridge the gap between fitting the model in each group uniquely and fitting a single-group model where we ignore nesting altogether. The parameters we set equal benefit from increased power because it is not diluted by the smaller sub-samples and reduce the number of parameters we need to interpret. One common approach is to start with the type of model we first fit, with all parameters unequal, and then progressively build in equality constraints and test whether they reduce the fit of the model. We can do this in two ways, either through the syntax (changing labels like <code>c(Mi, Fi)</code> to be the same like <code>c(i, i)</code>) or through the argument <code>group.equal</code> in the model fitting function. The first approach gives us more control, but can be tedious in large models, while the latter is less precise but quick. For instance, if we want to constrain the factor means equal across groups, we can simply include <code>means</code> in the <code>group.equal</code> argument. We can see the results below.</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="06-nesting.html#cb274-1" aria-hidden="true" tabindex="-1"></a>mult.g3 <span class="ot">&lt;-</span> <span class="st">&quot;int =~ 1*sci.1 + 1*sci.2 + 1*sci.3 + 1*sci.4</span></span>
<span id="cb274-2"><a href="06-nesting.html#cb274-2" aria-hidden="true" tabindex="-1"></a><span class="st">           slp =~ 0*sci.1 + 1*sci.2 + 2*sci.3 + 3*sci.4&quot;</span></span>
<span id="cb274-3"><a href="06-nesting.html#cb274-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb274-4"><a href="06-nesting.html#cb274-4" aria-hidden="true" tabindex="-1"></a>mult.g3.fit <span class="ot">&lt;-</span> <span class="fu">growth</span>(mult.g3,</span>
<span id="cb274-5"><a href="06-nesting.html#cb274-5" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> achieve.wide,</span>
<span id="cb274-6"><a href="06-nesting.html#cb274-6" aria-hidden="true" tabindex="-1"></a>                      <span class="at">group =</span> <span class="st">&quot;male&quot;</span>,</span>
<span id="cb274-7"><a href="06-nesting.html#cb274-7" aria-hidden="true" tabindex="-1"></a>                      <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">&quot;means&quot;</span>),</span>
<span id="cb274-8"><a href="06-nesting.html#cb274-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">estimator =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb274-9"><a href="06-nesting.html#cb274-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">missing =</span> <span class="st">&quot;FIML&quot;</span>)</span>
<span id="cb274-10"><a href="06-nesting.html#cb274-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb274-11"><a href="06-nesting.html#cb274-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mult.g3.fit, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">estimates =</span> <span class="cn">TRUE</span>, </span>
<span id="cb274-12"><a href="06-nesting.html#cb274-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">standardize =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-10 ended normally after 162 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        18
##   Number of equality constraints                     2
##                                                       
##   Number of observations per group:               Used       Total
##     1                                              576         600
##     0                                              624         637
##   Number of missing patterns per group:                           
##     1                                               15            
##     0                                               15            
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                                71.847
##   Degrees of freedom                                12
##   P-value (Chi-square)                           0.000
##   Test statistic for each group:
##     1                                           37.058
##     0                                           34.789
## 
## Model Test Baseline Model:
## 
##   Test statistic                              3772.258
##   Degrees of freedom                                12
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.984
##   Tucker-Lewis Index (TLI)                       0.984
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)             -12018.943
##   Loglikelihood unrestricted model (H1)     -11983.019
##                                                       
##   Akaike (AIC)                               24069.886
##   Bayesian (BIC)                             24151.327
##   Sample-size adjusted Bayesian (BIC)        24100.505
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.091
##   90 Percent confidence interval - lower         0.072
##   90 Percent confidence interval - upper         0.112
##   P-value RMSEA &lt;= 0.05                          0.000
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.058
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Observed
##   Observed information based on                Hessian
## 
## 
## Group 1 [1]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int =~                                                                
##     sci.1             1.000                              10.658    0.933
##     sci.2             1.000                              10.658    0.901
##     sci.3             1.000                              10.658    0.857
##     sci.4             1.000                              10.658    0.764
##   slp =~                                                                
##     sci.1             0.000                               0.000    0.000
##     sci.2             1.000                               1.822    0.154
##     sci.3             2.000                               3.643    0.293
##     sci.4             3.000                               5.465    0.392
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int ~~                                                                
##     slp               4.638    1.697    2.733    0.006    0.239    0.239
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1             0.000                               0.000    0.000
##    .sci.2             0.000                               0.000    0.000
##    .sci.3             0.000                               0.000    0.000
##    .sci.4             0.000                               0.000    0.000
##     int     (.20.)   60.622    0.295  205.481    0.000    5.688    5.688
##     slp     (.21.)    2.037    0.090   22.661    0.000    1.118    1.118
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1            17.021    2.367    7.190    0.000   17.021    0.130
##    .sci.2            13.673    1.541    8.872    0.000   13.673    0.098
##    .sci.3             9.399    1.557    6.035    0.000    9.399    0.061
##    .sci.4            23.359    3.312    7.054    0.000   23.359    0.120
##     int             113.598    7.692   14.768    0.000    1.000    1.000
##     slp               3.318    0.710    4.674    0.000    1.000    1.000
## 
## 
## Group 2 [0]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int =~                                                                
##     sci.1             1.000                               8.773    0.936
##     sci.2             1.000                               8.773    0.894
##     sci.3             1.000                               8.773    0.844
##     sci.4             1.000                               8.773    0.749
##   slp =~                                                                
##     sci.1             0.000                               0.000    0.000
##     sci.2             1.000                               1.975    0.201
##     sci.3             2.000                               3.949    0.380
##     sci.4             3.000                               5.924    0.505
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int ~~                                                                
##     slp               1.853    1.241    1.494    0.135    0.107    0.107
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1             0.000                               0.000    0.000
##    .sci.2             0.000                               0.000    0.000
##    .sci.3             0.000                               0.000    0.000
##    .sci.4             0.000                               0.000    0.000
##     int     (.20.)   60.622    0.295  205.481    0.000    6.910    6.910
##     slp     (.21.)    2.037    0.090   22.661    0.000    1.031    1.031
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1            10.894    1.725    6.315    0.000   10.894    0.124
##    .sci.2            11.772    1.171   10.053    0.000   11.772    0.122
##    .sci.3             8.040    1.165    6.902    0.000    8.040    0.074
##    .sci.4            14.177    2.357    6.015    0.000   14.177    0.103
##     int              76.967    5.013   15.354    0.000    1.000    1.000
##     slp               3.899    0.550    7.086    0.000    1.000    1.000</code></pre>
<p>Now note that the factor means (labels <code>.20.</code> and <code>.21.</code>) are equal across males and females. We could mix and match syntax and argument constraints if we like; like many things in SEM, we can have full control as long as we keep things organized. We can test whether this more constrained model fits significantly worse than the maximally-different model using a likelihood ratio test.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="06-nesting.html#cb276-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(mult.g1.fit, mult.g3.fit)</span></code></pre></div>
<pre><code>## Chi-Squared Difference Test
## 
##             Df   AIC   BIC  Chisq Chisq diff Df diff Pr(&gt;Chisq)   
## mult.g1.fit 10 24064 24155 61.451                                 
## mult.g3.fit 12 24070 24151 71.847     10.397       2   0.005526 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Here it appears that constraining the factor means does significantly decrease model fit, so we wouldn’t conclude that this constraint is appropriate. We could do this kind of testing with other parameters if we chose, although we won’t here for space and simplicity. The complexity and utility of the multiple groups models is not something we can explore fully here, and interested readers can find a much larger literature on these kinds of models if they wish to implement them in their own research (see the manuscript for a general starting point).</p>
</div>
<div id="fixed-effect-approach" class="section level2 hasAnchor">
<h2>Fixed Effect Approach<a href="06-nesting.html#fixed-effect-approach" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The fixed effect approach is (rarely for quantitative methods) exactly what it sounds like in the context of mixed-effect models, we simply include our grouping variable as a fixed effect in the model. This has the convenience of account for unmeasured or otherwise unmodeled differences between groups that might bias the effects. In the most common use of the fixed-effects approach, we account for intercept differences by including a main effect of the group. In the context of our data example, we will model the effect of <code>site</code> on science achievement using a fixed approach. Within the <code>lmer()</code> syntax, we can use the short-cute of <code>factor(site)</code> to generate a series of dummy-codes, where <code>site == 1</code> is the reference category. We can see the results of this below.</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="06-nesting.html#cb278-1" aria-hidden="true" tabindex="-1"></a>fixed.mlm1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(sci <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">+</span> <span class="fu">factor</span>(site) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">|</span> id),</span>
<span id="cb278-2"><a href="06-nesting.html#cb278-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action =</span> na.omit,</span>
<span id="cb278-3"><a href="06-nesting.html#cb278-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">REML =</span> <span class="cn">TRUE</span>,</span>
<span id="cb278-4"><a href="06-nesting.html#cb278-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> achieve)</span>
<span id="cb278-5"><a href="06-nesting.html#cb278-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fixed.mlm1, <span class="at">correlation =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sci ~ 1 + wave + factor(site) + (1 + wave | id)
##    Data: achieve
## 
## REML criterion at convergence: 24082.3
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.5642 -0.4218  0.0130  0.4559  4.2084 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  id       (Intercept) 94.706   9.732         
##           wave         4.048   2.012    -0.10
##  Residual             12.355   3.515         
## Number of obs: 3643, groups:  id, 1200
## 
## Fixed effects:
##                 Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)     58.59757    0.56691 1247.30204 103.363   &lt;2e-16 ***
## wave             1.98858    0.08722  861.42609  22.800   &lt;2e-16 ***
## factor(site)2    1.58400    0.86061 1183.63740   1.841   0.0659 .  
## factor(site)3    0.40383    0.89404 1189.48203   0.452   0.6516    
## factor(site)4    0.25571    0.83030 1186.72497   0.308   0.7582    
## factor(site)5   -2.21401    1.05705 1193.40187  -2.095   0.0364 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note that the <code>(Intercept)</code> term is the intercept for Site 1 and each of the effects <code>factor(site)*</code> indicate the relative difference from that term for the other sites. If we wished to use an absolute coding scheme, we change the <code>1</code> to a <code>0</code> (indicating that we don’t wish to estimate a reference intercept) and re-estimate the model.</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="06-nesting.html#cb280-1" aria-hidden="true" tabindex="-1"></a>fixed.mlm2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(sci <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> wave <span class="sc">+</span> <span class="fu">factor</span>(site) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">|</span> id),</span>
<span id="cb280-2"><a href="06-nesting.html#cb280-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action =</span> na.omit,</span>
<span id="cb280-3"><a href="06-nesting.html#cb280-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">REML =</span> <span class="cn">TRUE</span>,</span>
<span id="cb280-4"><a href="06-nesting.html#cb280-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> achieve)</span>
<span id="cb280-5"><a href="06-nesting.html#cb280-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fixed.mlm2, <span class="at">correlation =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sci ~ 0 + wave + factor(site) + (1 + wave | id)
##    Data: achieve
## 
## REML criterion at convergence: 24082.3
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.5642 -0.4218  0.0130  0.4559  4.2084 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  id       (Intercept) 94.706   9.732         
##           wave         4.048   2.012    -0.10
##  Residual             12.355   3.515         
## Number of obs: 3643, groups:  id, 1200
## 
## Fixed effects:
##                Estimate Std. Error        df t value Pr(&gt;|t|)    
## wave          1.989e+00  8.722e-02 8.614e+02   22.80   &lt;2e-16 ***
## factor(site)1 5.860e+01  5.669e-01 1.247e+03  103.36   &lt;2e-16 ***
## factor(site)2 6.018e+01  6.675e-01 1.226e+03   90.16   &lt;2e-16 ***
## factor(site)3 5.900e+01  7.105e-01 1.240e+03   83.04   &lt;2e-16 ***
## factor(site)4 5.885e+01  6.287e-01 1.248e+03   93.61   &lt;2e-16 ***
## factor(site)5 5.638e+01  9.073e-01 1.231e+03   62.14   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>These results are equivalent to the first coding scheme but we get the intercept estimate for each site instead of computing differences from a chosen site (note the change in what the inference test tells us).</p>
<p>Like mentioned above, the fixed effect approach is most commonly used for intercept differences, but can logically be extended to account for effect differences across sites (or another grouping variable). We can accomplish this by modeling the interaction of site with our time predictor like below.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="06-nesting.html#cb282-1" aria-hidden="true" tabindex="-1"></a>fixed.mlm3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(sci <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">+</span> <span class="fu">factor</span>(site) <span class="sc">+</span> wave<span class="sc">:</span><span class="fu">factor</span>(site) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">|</span> id),</span>
<span id="cb282-2"><a href="06-nesting.html#cb282-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action =</span> na.omit,</span>
<span id="cb282-3"><a href="06-nesting.html#cb282-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">REML =</span> <span class="cn">TRUE</span>,</span>
<span id="cb282-4"><a href="06-nesting.html#cb282-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> achieve)</span>
<span id="cb282-5"><a href="06-nesting.html#cb282-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fixed.mlm3, <span class="at">correlation =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sci ~ 1 + wave + factor(site) + wave:factor(site) + (1 + wave |  
##     id)
##    Data: achieve
## 
## REML criterion at convergence: 24076.6
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.5317 -0.4176  0.0117  0.4573  4.2531 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr 
##  id       (Intercept) 94.674   9.730         
##           wave         3.997   1.999    -0.09
##  Residual             12.365   3.516         
## Number of obs: 3643, groups:  id, 1200
## 
## Fixed effects:
##                      Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)          58.40288    0.59914 1154.84387  97.477   &lt;2e-16 ***
## wave                  2.13593    0.17030  972.01896  12.542   &lt;2e-16 ***
## factor(site)2         1.74603    0.92295 1120.17538   1.892   0.0588 .  
## factor(site)3         1.10856    0.96191 1134.56799   1.152   0.2494    
## factor(site)4         0.03638    0.89457 1141.90712   0.041   0.9676    
## factor(site)5        -1.45252    1.13802 1139.05119  -1.276   0.2021    
## wave:factor(site)2   -0.12248    0.25311  860.24886  -0.484   0.6286    
## wave:factor(site)3   -0.52808    0.26582  877.36598  -1.987   0.0473 *  
## wave:factor(site)4    0.15811    0.24806  912.54265   0.637   0.5240    
## wave:factor(site)5   -0.56471    0.31249  860.82672  -1.807   0.0711 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Here we return to the reference coding to test whether the effect of wave differs across sites from the reference. We can see how parameter do tend to multiply rapidly, however, with a relatively small set of grouping levels (here we only have 5 site), this is manageable. With larger numbers of groups (e.g., families), this approach would become less tenable. Note that we still have our random effect across individuals, but we’ve removed site-level differences from those estimates through the use of the fixed effects approach. Very often we will not interpret the associated parameters, but include them to de-confound our estimates of interest. Another thing to mention is that this isn’t a “pure” form of the fixed-effects approach, since we still include the random effect of individual. The purely fixed-effect approach is more common/appropriate for group-based clustered (e.g., site, country) rather than individual-based clustering (as we always have in longitudinal data) since we cannot include individual level fixed-effects without breaking the model (it isn’t identified).</p>
</div>
<div id="random-effect-approach" class="section level2 hasAnchor">
<h2>Random Effect Approach<a href="06-nesting.html#random-effect-approach" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If we want to move into accounting for grouping variables with many levels, the random effects framework provides a nice and ready solution. Indeed, we have been using it for the nesting of repeated measures within individuals this whole time. Within MEMs, we can include higher levels of nesting by expanding the structure of the random effects in our model syntax. Here we expand our classic <code>(1 + wave | id)</code> to include the higher level of nesting individuals within schools <code>(1 + wave | school/id)</code>.</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="06-nesting.html#cb284-1" aria-hidden="true" tabindex="-1"></a>rand.mlm <span class="ot">&lt;-</span> <span class="fu">lmer</span>(sci <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> wave <span class="sc">|</span> school<span class="sc">/</span>id),</span>
<span id="cb284-2"><a href="06-nesting.html#cb284-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">na.action =</span> na.omit,</span>
<span id="cb284-3"><a href="06-nesting.html#cb284-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">REML =</span> <span class="cn">TRUE</span>,</span>
<span id="cb284-4"><a href="06-nesting.html#cb284-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> achieve)</span>
<span id="cb284-5"><a href="06-nesting.html#cb284-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb284-6"><a href="06-nesting.html#cb284-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rand.mlm, <span class="at">correlation =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: sci ~ 1 + wave + (1 + wave | school/id)
##    Data: achieve
## 
## REML criterion at convergence: 23997.8
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -4.4223 -0.4199  0.0095  0.4600  4.3844 
## 
## Random effects:
##  Groups    Name        Variance Std.Dev. Corr 
##  id:school (Intercept) 84.8280  9.2102        
##            wave         3.5754  1.8909   -0.10
##  school    (Intercept) 12.8267  3.5814        
##            wave         0.5727  0.7568   -0.14
##  Residual              12.3157  3.5094        
## Number of obs: 3643, groups:  id:school, 1200; school, 41
## 
## Fixed effects:
##             Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)  58.4281     0.6513 35.6623   89.71  &lt; 2e-16 ***
## wave          1.9598     0.1516 34.9412   12.92 7.14e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The ordering of <code>school/id</code> is important otherwise we have schools nested within individual which will make the model sad (it’s true). We can check that we’ve done this in the model summary where we have <span class="math inline">\(1200\)</span> individuals nested within schools (<code>id:school</code>) and <span class="math inline">\(41\)</span> schools. If we compare this model to the model where we ignore nesting within school, we will notice that the fixed effects have not changed that much, but that our estimate of individual-level variance has been broken up into individual- and school-level variability. This situation is fairly common (although not guaranteed), with fixed effects that are relatively robust to omitting higher levels of nesting, but mis-attributed variance estimates at lower levels of nesting that over-estimate inter-individual variance.</p>
<p>Compared with the fairly natural extension of the MEMs to higher levels of nesting, multilevel SEM estimation is much more challenging and the current options in R are fairly limited. For instance, <strong>lavaan</strong> currently only allows complete case continuous data with a random intercept at the higher level of nesting (see the current <a href="https://lavaan.ugent.be/tutorial/multilevel.html">tutorial</a>). This is an active area of improvement so additional options are likely to be available soon. We provide <strong>Mplus</strong> examples of the full model that more closely resembles the MLM above. However, for completeness, we fit the model we can in <strong>lavaan</strong> below.</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="06-nesting.html#cb286-1" aria-hidden="true" tabindex="-1"></a>mlsem <span class="ot">&lt;-</span> <span class="st">&quot;</span></span>
<span id="cb286-2"><a href="06-nesting.html#cb286-2" aria-hidden="true" tabindex="-1"></a><span class="st">           level: 1</span></span>
<span id="cb286-3"><a href="06-nesting.html#cb286-3" aria-hidden="true" tabindex="-1"></a><span class="st">           int.w =~ 1*sci.1 + 1*sci.2 + 1*sci.3 + 1*sci.4</span></span>
<span id="cb286-4"><a href="06-nesting.html#cb286-4" aria-hidden="true" tabindex="-1"></a><span class="st">           slp.w =~ 0*sci.1 + 1*sci.2 + 2*sci.3 + 3*sci.4</span></span>
<span id="cb286-5"><a href="06-nesting.html#cb286-5" aria-hidden="true" tabindex="-1"></a><span class="st">           </span></span>
<span id="cb286-6"><a href="06-nesting.html#cb286-6" aria-hidden="true" tabindex="-1"></a><span class="st">           sci.1 ~~ a*sci.1</span></span>
<span id="cb286-7"><a href="06-nesting.html#cb286-7" aria-hidden="true" tabindex="-1"></a><span class="st">           sci.2 ~~ a*sci.2</span></span>
<span id="cb286-8"><a href="06-nesting.html#cb286-8" aria-hidden="true" tabindex="-1"></a><span class="st">           sci.3 ~~ a*sci.3</span></span>
<span id="cb286-9"><a href="06-nesting.html#cb286-9" aria-hidden="true" tabindex="-1"></a><span class="st">           sci.4 ~~ a*sci.4</span></span>
<span id="cb286-10"><a href="06-nesting.html#cb286-10" aria-hidden="true" tabindex="-1"></a><span class="st">           </span></span>
<span id="cb286-11"><a href="06-nesting.html#cb286-11" aria-hidden="true" tabindex="-1"></a><span class="st">           level: 2</span></span>
<span id="cb286-12"><a href="06-nesting.html#cb286-12" aria-hidden="true" tabindex="-1"></a><span class="st">           int.b =~ 1*sci.1 + 1*sci.2 + 1*sci.3 + 1*sci.4</span></span>
<span id="cb286-13"><a href="06-nesting.html#cb286-13" aria-hidden="true" tabindex="-1"></a><span class="st">           </span></span>
<span id="cb286-14"><a href="06-nesting.html#cb286-14" aria-hidden="true" tabindex="-1"></a><span class="st">           sci.1 ~~ b*sci.1</span></span>
<span id="cb286-15"><a href="06-nesting.html#cb286-15" aria-hidden="true" tabindex="-1"></a><span class="st">           sci.2 ~~ b*sci.2</span></span>
<span id="cb286-16"><a href="06-nesting.html#cb286-16" aria-hidden="true" tabindex="-1"></a><span class="st">           sci.3 ~~ b*sci.3</span></span>
<span id="cb286-17"><a href="06-nesting.html#cb286-17" aria-hidden="true" tabindex="-1"></a><span class="st">           sci.4 ~~ b*sci.4&quot;</span></span>
<span id="cb286-18"><a href="06-nesting.html#cb286-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb286-19"><a href="06-nesting.html#cb286-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb286-20"><a href="06-nesting.html#cb286-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb286-21"><a href="06-nesting.html#cb286-21" aria-hidden="true" tabindex="-1"></a>mlsem.fit <span class="ot">&lt;-</span> <span class="fu">growth</span>(mlsem,</span>
<span id="cb286-22"><a href="06-nesting.html#cb286-22" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> achieve.wide,</span>
<span id="cb286-23"><a href="06-nesting.html#cb286-23" aria-hidden="true" tabindex="-1"></a>                    <span class="at">cluster =</span> <span class="st">&quot;school&quot;</span>,</span>
<span id="cb286-24"><a href="06-nesting.html#cb286-24" aria-hidden="true" tabindex="-1"></a>                    <span class="at">estimator =</span> <span class="st">&quot;ML&quot;</span>,</span>
<span id="cb286-25"><a href="06-nesting.html#cb286-25" aria-hidden="true" tabindex="-1"></a>                    <span class="at">missing =</span> <span class="st">&quot;listwise&quot;</span>,</span>
<span id="cb286-26"><a href="06-nesting.html#cb286-26" aria-hidden="true" tabindex="-1"></a>                    <span class="at">optim.method =</span> <span class="st">&quot;em&quot;</span>)</span>
<span id="cb286-27"><a href="06-nesting.html#cb286-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb286-28"><a href="06-nesting.html#cb286-28" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mlsem.fit, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>, <span class="at">estimates =</span> <span class="cn">TRUE</span>, </span>
<span id="cb286-29"><a href="06-nesting.html#cb286-29" aria-hidden="true" tabindex="-1"></a>        <span class="at">standardize =</span> <span class="cn">TRUE</span>, <span class="at">rsquare =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## lavaan 0.6-10 ended normally after 40 iterations
## 
##   Estimator                                         ML
##   Optimization method                               EM
##   Number of model parameters                        15
##   Number of equality constraints                     6
##                                                       
##                                                   Used       Total
##   Number of observations                           482        1237
##   Number of clusters [school]                       35            
##                                                                   
## Model Test User Model:
##                                                       
##   Test statistic                                68.230
##   Degrees of freedom                                15
##   P-value (Chi-square)                           0.000
## 
## Model Test Baseline Model:
## 
##   Test statistic                              2526.704
##   Degrees of freedom                                12
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.979
##   Tucker-Lewis Index (TLI)                       0.983
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)              -5969.695
##   Loglikelihood unrestricted model (H1)      -5935.580
##                                                       
##   Akaike (AIC)                               11957.390
##   Bayesian (BIC)                             11994.991
##   Sample-size adjusted Bayesian (BIC)        11966.426
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.086
##   90 Percent confidence interval - lower         0.066
##   90 Percent confidence interval - upper         0.107
##   P-value RMSEA &lt;= 0.05                          0.002
## 
## Standardized Root Mean Square Residual (corr metric):
## 
##   SRMR (within covariance matrix)                0.012
##   SRMR (between covariance matrix)               0.025
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Observed
##   Observed information based on                Hessian
## 
## 
## Level 1 [within]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int.w =~                                                              
##     sci.1             1.000                               8.513    0.947
##     sci.2             1.000                               8.513    0.915
##     sci.3             1.000                               8.513    0.858
##     sci.4             1.000                               8.513    0.789
##   slp.w =~                                                              
##     sci.1             0.000                               0.000    0.000
##     sci.2             1.000                               1.750    0.188
##     sci.3             2.000                               3.501    0.353
##     sci.4             3.000                               5.251    0.487
## 
## Covariances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int.w ~~                                                              
##     slp.w             1.317    0.922    1.428    0.153    0.088    0.088
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1             0.000                               0.000    0.000
##    .sci.2             0.000                               0.000    0.000
##    .sci.3             0.000                               0.000    0.000
##    .sci.4             0.000                               0.000    0.000
##     int.w             3.402    0.427    7.965    0.000    0.400    0.400
##     slp.w             2.098    0.134   15.668    0.000    1.198    1.198
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1      (a)    8.373    0.395   21.224    0.000    8.373    0.104
##    .sci.2      (a)    8.373    0.395   21.224    0.000    8.373    0.097
##    .sci.3      (a)    8.373    0.395   21.224    0.000    8.373    0.085
##    .sci.4      (a)    8.373    0.395   21.224    0.000    8.373    0.072
##     int.w            72.471    5.263   13.771    0.000    1.000    1.000
##     slp.w             3.063    0.324    9.441    0.000    1.000    1.000
## 
## R-Square:
##                    Estimate
##     sci.1             0.896
##     sci.2             0.903
##     sci.3             0.915
##     sci.4             0.928
## 
## 
## Level 2 [school]:
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   int.b =~                                                              
##     sci.1             1.000                               4.083    0.969
##     sci.2             1.000                               4.083    0.969
##     sci.3             1.000                               4.083    0.969
##     sci.4             1.000                               4.083    0.969
## 
## Intercepts:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1             0.000                               0.000    0.000
##    .sci.2             0.000                               0.000    0.000
##    .sci.3             0.000                               0.000    0.000
##    .sci.4             0.000                               0.000    0.000
##     int.b            59.767    0.427  139.930    0.000   14.639   14.639
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .sci.1      (b)    1.090    0.302    3.609    0.000    1.090    0.061
##    .sci.2      (b)    1.090    0.302    3.609    0.000    1.090    0.061
##    .sci.3      (b)    1.090    0.302    3.609    0.000    1.090    0.061
##    .sci.4      (b)    1.090    0.302    3.609    0.000    1.090    0.061
##     int.b            16.668    6.440    2.588    0.010    1.000    1.000
## 
## R-Square:
##                    Estimate
##     sci.1             0.939
##     sci.2             0.939
##     sci.3             0.939
##     sci.4             0.939</code></pre>
<p>Here we get a similar layout for the results as the multiple groups model, with the within estimates first, and then the school-level estimates next. We needed to set the residuals to be homoscedastic to achieve convergence here, but in principle these can be allowed to vary.</p>
</div>
<div id="cluster-correction" class="section level2 hasAnchor">
<h2>Cluster Correction<a href="06-nesting.html#cluster-correction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The fixed effects point estimates within the model tend to be robust to the omission of higher levels of nesting, however, their standard errors do tend to be inaccurate. As such, sometimes we might wish to simply not interpret the variance components and focus on regression coefficients or other parts of our model. This might be less frequent in growth modeling, but for completeness we will consider this type of application. In this instance, we can simply implement a cluster-correction to our standard errors and then proceed as usual to interpret the model parameters. To our knowledge, this is not currently an option in R, so we provide the <strong>Mplus</strong> syntax to do so below.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="05-covariates.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="07-datasets.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["twitter", "facebook", "linkedin", "google", "weibo", "instapaper"],
"google": false,
"instapper": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/McCormickNeuro/longitudinal-primer/edit/main/06-nesting.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section",
"depth": 2,
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
