---
title: "Latent Growth Factors as Predictors of Distal Outcomes"
output:
  distill::distill_article:
    css: ../../../styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[<i class="fas fa-file-download"></i> PDF](36.McCormick-Curran-Hancock-2024-PsychMethods.pdf) | [<i class="fas fa-quote-left"></i><i class="fas fa-quote-right"></i> BibTeX Citation](cite.bib) | [<i class="fas fa-link"></i> DOI](https://doi.org/10.1037/met0000642) | [<i class="ai ai-open-materials"></i> Code](https://doi.org/10.17605/OSF.IO/FZUBT)


### Abstract
A currently overlooked application of the latent curve model (LCM) is its use in assessing the consequences of development patterns of change—that is as a predictor of distal outcomes. However, there are additional complications for appropriately specifying and interpreting the distal outcome LCM. Here, we develop a general framework for understanding the sensitivity of the distal outcome LCM to the choice of time coding, focusing on the regressions of the distal outcome on the latent growth factors. Using artificial and real-data examples, we highlight the unexpected changes in the regression of the slope factor which stand in contrast to prior work on time coding effects, and develop a framework for estimating the distal outcome LCM at a point in the trajectory—known as the aperture—which maximizes the interpretability of the effects.We also outline a prioritization approach developed for assessing incremental validity to obtain consistently interpretable estimates of the effect of the slope. Throughout, we emphasize practical steps for understanding these changing predictive effects, including graphical approaches for assessing regions of significance similar to those used to probe interaction effects. We conclude by providing recommendations for applied research using these models and outline an agenda for future work in this area.

**Citation:** McCormick, E. M., Curran, P. J., Hancock, G. R. (2024). Latent Growth Factors as Predictors of Distal Outcomes. *Psychological Methods*, *In Press*. 