---
title: "Subjective social status and neural processing of race in Mexican-American adolescents."
output:
  distill::distill_article:
    css: ../../../styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[<i class="fas fa-file-download"></i> PDF](static/pubs/10-2018-DevPsychop/10.Muscatell-McCormick-Telzer-2018-DevPsychopathol.pdf) | [<i class="fas fa-quote-left"></i><i class="fas fa-quote-right"></i> BibTeX Citation](static/pubs/10-2018-DevPsychop/cite.bib) | [<i class="ai ai-open-data"></i> Dataset](https://neurovault.org/collections/6076/) | [<i class="fas fa-link"></i> DOI](https://doi.org/10.1017/S0954579418000949)

### Abstract
Adolescence is a sensitive period for sociocultural development in which facets of social identity, including social status and race, become especially salient. Despite the heightened importance of both social status and race during this developmental period, no known work has examined how individual differences in social status influence perceptions of race in adolescents. Thus, in the present study, we investigated how both subjective social status and objective socioeconomic status (SES) influence neural responses to race. Twenty-three Mexican American adolescents (15 females; mean age = 17.22 years) were scanned using functional magnetic resonance imaging while they viewed Black and White faces in a standard labeling task. Adolescents rated their subjective social status in US society, while their parents responded to questions about their educational background, occupation, and economic strain (objective SES). Results demonstrated a negative association between subjective social status and neural responses in the amygdala, fusiform face area, and medial prefrontal cortex when adolescents viewed Black (relative to White) faces. In other words, adolescents with lower subjective social status showed greater activity in neural regions involved in processing salience, perceptual expertise, and thinking about the minds of others when they viewed images of Black faces, suggesting enhanced salience of race for these youth. There was no relationship between objective SES and neural responses to the faces. Moreover, instructing participants to focus on the gender or emotion expression on the face attenuated the relationship between subjective social status and neural processing of race. Together, these results demonstrate that subjective social status shapes the way the brain responds to race, which may have implications for psychopathology.

**Citation:** Muscatell, K. A., McCormick, E. M., & Telzer, E. H. (2018). Subjective social status and neural processing of race in Mexican-American adolescents. *Development and Psychopathology, 30*(5), 1837-1848.