---
title: "A multivariate growth curve model for three-level data."
output:
  distill::distill_article:
    css: ../../../styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[<i class="fas fa-file-download"></i> PDF](34.Curran-Strauss-McCormick-McGinley-2023-APA.pdf) | [<i class="fas fa-quote-left"></i><i class="fas fa-quote-right"></i> BibTeX Citation](cite.bib)

### Abstract

One of the most vexing challenges that has faced the behavioral sciences over the past century has been how to optimally measure, summarize, and predict individual variability in stability and change over time. It has long been known that a multitude of advantages are associated with the collection and analysis of repeated measures data; indeed, longitudinal data have become nearly requisite in many disciplines within the behavioral sciences. The challenge of how best to empirically capture individual change cuts across every aspect of the empirical research endeavor, including study design, psychometric measurement, subject sampling, data analysis, and substantive interpretation. Although many textbooks have been devoted to each of these research dimensions, here we have the much more modest goal of exploring just one specific type of longitudinal data analytic method: the multivariate growth model.

**Citation:** Curran, P.J., Strauss, C., McCormick, E.M., & McGinley, J.S. (2023). A multivariate growth curve model for three-level data. In H. Cooper (Ed.) APA Handbook of Research Methods in Psychology, Second Edition. Washington, DC: American Psychological Association.