---
title: "The neural development of prosocial behavior from childhood to adolescence."
output:
  distill::distill_article:
    css: ../../../styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[<i class="fas fa-file-download"></i> PDF](static/pubs/16-2019-SCAN/16.Do-McCormick-Telzer-2019-SCAN.pdf) | [<i class="fas fa-quote-left"></i><i class="fas fa-quote-right"></i> BibTeX Citation](static/pubs/16-2019-SCAN/cite.bib) | [<i class="ai ai-open-data"></i> Dataset](https://neurovault.org/collections/3986/) | [<i class="fas fa-link"></i> DOI](https://doi.org/10.1093/scan/nsy117)

### Abstract
AThe transition from childhood to adolescence is marked by increasingly sophisticated social cognitive abilities that are paralleled by significant functional maturation of the brain. However, the role of social and neurobiological development in facilitating age differences in prosocial behavior remains unclear. Using a cross-sectional sample of children and adolescents (n = 51; 8–16 years), we examined the age-related correlates of prosocial behavior. Youth made costly and non-costly prosocial decisions to anonymous peers during a functional magnetic resonance imaging scan. Among a subsample of youth who made prosocial decisions (n = 35), we found quadratic age differences in neural activation that peaked in early adolescence relative to childhood and older adolescence. In particular, early adolescents showed heightened recruitment of the posterior superior temporal sulcus (pSTS), temporal pole and inferior frontal gyrus (IFG) when engaging in costly prosocial behavior at the expense of gaining a reward, whereas they evoked heightened pSTS and dorsolateral prefrontal cortex/IFG activation when engaging in costly vs non-costly forms of prosocial behavior. Given that we did not find age differences in prosocial behavior, this suggests that early adolescents show unique patterns of brain activation to inform similar levels of prosocial behavior.

**Citation:** Do, K. T., McCormick, E. M., & Telzer, E. H. (2019). The neural development of prosocial behavior from childhood to adolescence. *Social Cognitive and Affective Neuroscience, 14*(2), 129-139.