---
title: "Behavioral and neural dysregulation to social rewards and links to internalizing symptoms in adolescents."
output:
  distill::distill_article:
    css: ../../../styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[<i class="fas fa-file-download"></i> PDF](static/pubs/18-2019-Frontiers/18.Kwon-Ivory-McCormick-Telzer-2019-Frontiers.pdf) | [<i class="fas fa-quote-left"></i><i class="fas fa-quote-right"></i> BibTeX Citation](static/pubs/18-2019-Frontiers/cite.bib) | [<i class="ai ai-open-data"></i> Dataset](https://neurovault.org/collections/5338/) | [<i class="fas fa-link"></i> DOI](https://doi.org/10.3389/fnbeh.2019.00158)

### Abstract
Adolescence is a time of unique sensitivity to socially salient stimuli such as social rewards. This period overlaps with the onset of psychopathology such as internalizing and externalizing symptoms. In the current studies, we examined behavioral and neural patterns of dysregulation to social rewards and threats, and links to internalizing and externalizing symptoms in youths. In study 1, we used a social Go/NoGo cognitive control task using peer faces to test for age-related behavioral differences in inhibitory failures in adolescents (N = 53, M<sub>age</sub> = 13.37 years), and adults (N = 51, M<sub>age</sub> = 43.71 years). In study 2, an independent adolescent sample (N = 51, M<sub>age</sub> = 13.98 years) completed a similar social Go/NoGo cognitive control task during fMRI. Results show that adolescents had greater inhibitory failures – as measured by false alarm rate – to both social reward and threat cues than adults, and more so to social reward than threat cues. Greater inhibitory failures to social reward than threat cues were associated with greater internalizing symptoms, but were not significantly related to externalizing symptoms. At the neural level, greater inhibitory failures to social reward than threat cues as well as greater internalizing symptoms were both associated with heightened amygdala-ventral striatum connectivity. Our findings indicate that subcortico-subcortical connectivity, which is deemed to occur chronologically earlier and thus necessary for subcortico-cortical circuits, may serve as an early biomarker for emotion dysregulation and a risk factor for internalizing symptoms.

**Citation:** Kwon, S-J., Ivory, S. L., McCormick, E. M., & Telzer, E. H. (2019). Behavioral and neural dysregulation to social rewards and links to internalizing symptoms in adolescents. *Frontiers in Behavioral Neuroscience, 13*, 158.