---
title: "Apples to apples? Neural correlates of emotion regulation differences between high and low risk adolescents."
output:
  distill::distill_article:
    css: ../../../styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[<i class="fas fa-file-download"></i> PDF](19.Perino-Moreira-McCormick-Telzer-2019-SCAN.pdf) | [<i class="fas fa-quote-left"></i><i class="fas fa-quote-right"></i> BibTeX Citation](cite.bib) | [<i class="ai ai-open-data"></i> Dataset](https://neurovault.org/collections/4081/) | [<i class="fas fa-link"></i> DOI](https://doi.org/10.1093/scan/nsz063)

### Abstract
Adolescence has been noted as a period of increased risk taking. The literature on normative neurodevelopment implicates aberrant activation of affective and regulatory regions as key to inhibitory failures. However, many of these studies have not included adolescents engaging in high rates of risky behavior, making generalizations to the most at-risk populations potentially problematic. We conducted a comparative study of nondelinquent community (n = 24, mean age = 15.8 years, 12 female) and delinquent adolescents (n = 24, mean age = 16.2 years, 12 female) who completed a cognitive control task during functional magnetic resonance imaging, where behavioral inhibition was assessed in the presence of appetitive and aversive socioaffective cues. Community adolescents showed poorer behavioral regulation to appetitive relative to aversive cues, whereas the delinquent sample showed the opposite pattern. Recruitment of the inferior frontal gyrus, medial prefrontal cortex, and tempoparietal junction differentiated community and high-risk adolescents, as delinquent adolescents showed significantly greater recruitment when inhibiting their responses in the presence of aversive cues, while the community sample showed greater recruitment when inhibiting their responses in the presence of appetitive cues. Accounting for behavioral history may be key in understanding when adolescents will have regulatory difficulties, highlighting a need for comparative research into normative and nonnormative risk-taking trajectories.

**Citation:** Perino, M. T., Guassi Moreira, J. F., McCormick, E. M., & Telzer, E. H. (2019). Apples to apples? Neural correlates of emotion regulation differences between high and low risk adolescents. *Social Cognitive and Affective Neuroscience, 14*(2), 129-139.